# Generated by Django 3.2.7 on 2021-09-30 08:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your House Caretaker (e.g. Macharia John)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the house location', max_length=1000)),
                ('caretaker', models.ManyToManyField(help_text='Select a caretaker for this House', to='rent.Caretaker')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_entry', models.DateField(blank=True, null=True, verbose_name='Entry')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular rent across whole rentcase(s)', primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('p', 'Pending'), ('r', 'Underpaid'), ('G', 'Paid'), ('o', 'Overpaid')], default='p', help_text='Rent_payment', max_length=1)),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='rent.house')),
            ],
            options={
                'ordering': ['payment_date'],
            },
        ),
        migrations.AddField(
            model_name='house',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.tenant'),
        ),
    ]
